services:
  app:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: tortodelova-app
    env_file:
      - ../app.env
    volumes:
      - ../backend/app:/app/app
    depends_on:
      - database
      - rabbitmq
    restart: unless-stopped

  web-proxy:
    image: nginx:1.27-alpine
    container_name: tortodelova-nginx
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:80"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: tortodelova-rabbitmq
    ports:
      - "5672:5672"    # основной AMQP-порт
      - "15672:15672"  # web-интерфейс управления
    volumes:
      # Локальная директория для сохранения очередей между перезапусками
      - ../data/rabbitmq:/var/lib/rabbitmq
    restart: on-failure

  database:
    image: postgres:16
    container_name: tortodelova-postgres
    environment:
      POSTGRES_DB: tortodelova
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      # Локальная директория для сохранения данных БД
      - ../data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
